// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaSupermercado.Entities.Entities
{
    public partial class tbImpuestos
    {
        public tbImpuestos()
        {
            tbProductos = new HashSet<tbProductos>();
        }

        public int Impue_Id { get; set; }
        public decimal Impue_Descripcion { get; set; }
        public int Impue_UsuarioCreacion { get; set; }
        public DateTime Impue_FechaCreacion { get; set; }
        public int? Impue_UsuarioModificacion { get; set; }
        public DateTime? Impue_FechaModificacion { get; set; }
        public bool? Impue_Estado { get; set; }

        public virtual tbUsuarios Impue_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Impue_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductos { get; set; }
    }
}