// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaSupermercado.Entities.Entities
{
    public partial class tbLotes
    {
        public tbLotes()
        {
            tbVentasDetalle = new HashSet<tbVentasDetalle>();
        }

        public int Lotes_Id { get; set; }
        public DateTime Lotes_FechaVencimiento { get; set; }
        public int Produ_Id { get; set; }
        public int Lotes_Cantidad { get; set; }
        public int Sucur_Id { get; set; }
        [NotMapped]
        public string Produ_Descripcion { get; set; }
        [NotMapped]
        public string Sucur_Descripcion { get; set; }
        public int Lotes_UsuarioCreacion { get; set; }
        public DateTime Lotes_FechaCreacion { get; set; }
        public int? Lotes_UsuarioModificacion { get; set; }
        public DateTime? Lotes_FechaModificacion { get; set; }
        public bool? Lotes_Estado { get; set; }

        public virtual tbUsuarios Lotes_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Lotes_UsuarioModificacionNavigation { get; set; }
        public virtual tbProductos Produ { get; set; }
        public virtual tbSucursales Sucur { get; set; }
        public virtual ICollection<tbVentasDetalle> tbVentasDetalle { get; set; }
    }
}