// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaSupermercado.Entities.Entities
{
    public partial class tbPantallasPorRoles
    {
        public int Papro_Id { get; set; }
        public int Panta_Id { get; set; }
        public int? Roles_Id { get; set; }
        [NotMapped]
        public int? Pantalla { get; set; }
        [NotMapped]
        public string Panta_Descripcion { get; set; }
        public int Papro_UsuarioCreacion { get; set; }
        public DateTime Papro_FechaCreacion { get; set; }
        public int? Papro_UsuarioModificacion { get; set; }
        public DateTime? Papro_FechaModificacion { get; set; }
        public bool? Papro_Estado { get; set; }

        [NotMapped]
        public string UsuarioCreacion { get; set; }

        [NotMapped]
        public string UsuarioModificacion { get; set; }

        [NotMapped]
        public string Role_Rol { get; set; }

        public virtual tbPantallas Panta { get; set; }
        public virtual tbUsuarios Papro_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Papro_UsuarioModificacionNavigation { get; set; }
        public virtual tbRoles Roles { get; set; }
    }
}