// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaSupermercado.Entities.Entities
{
    public partial class tbProveedores
    {
        public tbProveedores()
        {
            tbProductos = new HashSet<tbProductos>();
        }

        public int Prove_Id { get; set; }
        public string Prove_Marca { get; set; }
        public string Prove_ContactoPrimerNombre { get; set; }
        public string Prove_ContactoSegundoNombre { get; set; }
        public string Prove_ContactoPrimerApellido { get; set; }
        public string Prove_ContactoSegundoApellido { get; set; }
        [NotMapped]
        public string UsuarioCreacion { get; set; }
        [NotMapped]
        public string UsuarioModificacion { get; set; }
        [NotMapped]

        public string Contacto { get; set; }
        public string Munic_Id { get; set; }
        [NotMapped]
        public string Munic_Descripcion { get; set; }

        public string Prove_Direccion { get; set; }
        public string Prove_Telefono { get; set; }
        public string Prove_Correo { get; set; }
        public string Prove_Notas { get; set; }
        public int Prove_UsuarioCreacion { get; set; }
        public DateTime Prove_FechaCreacion { get; set; }
        public int? Prove_UsuarioModificacion { get; set; }
        public DateTime? Prove_FechaModificacion { get; set; }
        public bool? Prove_Estado { get; set; }

        public virtual tbMunicipios Munic { get; set; }
        public virtual tbUsuarios Prove_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Prove_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductos { get; set; }
    }
}