// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaSupermercado.Entities.Entities
{
    public partial class tbSubcategorias
    {
        public tbSubcategorias()
        {
            tbProductos = new HashSet<tbProductos>();
        }

        public int Subca_Id { get; set; }
        public string Subca_Descripcion { get; set; }
        public int Categ_Id { get; set; }
        [NotMapped]
        public string Categ_Descripcion { get; set; }
        public string Subca_UsuarioCreacion { get; set; }
        public DateTime Subca_FechaCreacion { get; set; }
        public string Subca_UsuarioModificacion { get; set; }
        public DateTime? Subca_FechaModificacion { get; set; }
        public bool? Subca_Estado { get; set; }

        public virtual tbCategorias Categ { get; set; }
        public virtual tbUsuarios Subca_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Subca_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductos { get; set; }
    }
}