// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaSupermercado.Entities.Entities
{
    public partial class tbSucursales
    {
        public tbSucursales()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
            tbLotes = new HashSet<tbLotes>();
            tbVentasEncabezado = new HashSet<tbVentasEncabezado>();
        }

        public int Sucur_Id { get; set; }
        public string Sucur_Descripcion { get; set; }
        public string Munic_Id { get; set; }
        [NotMapped]
        public string Munic_Descripcion { get; set; }
        public string Sucur_Direccion { get; set; }
        public string Sucur_Telefono { get; set; }
        public string Sucur_UsuarioCreacion { get; set; }
        public DateTime Sucur_FechaCreacion { get; set; }
        public string Sucur_UsuarioModificacion { get; set; }
        public DateTime? Sucur_FechaModificacion { get; set; }
        public bool? Sucur_Estado { get; set; }

        public virtual tbMunicipios Munic { get; set; }
        public virtual tbUsuarios Sucur_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Sucur_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual ICollection<tbLotes> tbLotes { get; set; }
        public virtual ICollection<tbVentasEncabezado> tbVentasEncabezado { get; set; }
    }
}