// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaSupermercado.Entities.Entities
{
    public partial class tbVentasDetalle
    {
        public int Vende_Id { get; set; }
        public int Venen_Id { get; set; }
        public int Lotes_Id { get; set; }
        public int Vende_Cantidad { get; set; }
        public string Vende_UsuarioCreacion { get; set; }
        public DateTime Vende_FechaCreacion { get; set; }
        public string Vende_UsuarioModificacion { get; set; }
        public DateTime? Vende_FechaModificacion { get; set; }
        public bool? Vende_Estado { get; set; }

        public virtual tbLotes Lotes { get; set; }
        public virtual tbUsuarios Vende_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Vende_UsuarioModificacionNavigation { get; set; }
        public virtual tbVentasEncabezado Venen { get; set; }
    }
}