export class Cliente{
    clien_Id?:number;
    clien_Dni?:string;
    clien_PrimerNombre?:string;
    clien_SegundoNombre?:string;
    clien_PrimerApellido?:string;
    clien_SegundoApellido?:string;
    clien_NombreCompleto?:string;
    clien_Sexo?:string;
    sexo?:string;
    estad_Id?: number;
    clien_Telefono?: string;
    munic_Id?: string;
    deparid?: number;
    depardescrip?: string;
    clien_Direccion?: string;
    nombre?: string;
    estad_Descripcion?: string;
    munic_Descripcion?: string;
    totalClientesMesActual?:number;
    diferenciaClientesMesPasado?:number;
    usuarioCreacion?: string;
    usuarioModificacion?: string;
    clien_UsuarioCreacion?: number;
    clien_UsuarioModificacion?: number;
    clien_FechaCreacion?: number;
    clien_FechaModificacion?: string;
    genero?:string;
    cantidadVentas?:string;
}