export class Empleado{
    emple_Id?:number;
    emple_Dni?:String;
    emple_PrimerNombre?:String;
    emple_SegundoNombre?:String;
    emple_PrimerApellido?:String;
    emple_SegundoApellido?:String;
    emple_Sexo?:String;
    sexo?:string;
    estad_Id?: number;
    emple_Telefono?: string;
    emple_Correo?: string;
    munic_Id?: string;
    deparid?: number;
    depardescrip?: string;
    emple_Direccion?: string;
    cargo_Id?: number;
    sucur_Id?: number;
    emple_NombreCompleto?: string;
    estad_Descripcion?: string;
    munic_Descripcion?: string;
    cargo_Descripcion?: string;
    sucur_Descripcion?: string;
    usuarioCreacion?: string;
    usuarioModificacion?: string;
    emple_UsuarioCreacion?: number;
    emple_UsuarioModificacion?: number;
    emple_FechaCreacion?: number;
    emple_FechaModificacion?: string;
}